name: pr-status-label
description: Set pull request statuses according labels
branding:
  icon: 'git-pull-request'
  color: 'blue'
runs:
  using: 'node12'
  main: './node_modules/probot/bin/probot.js'
